# -*- coding: utf-8 -*-
"""
Created on Mon Feb  8 16:03:55 2021

@author: akladke
"""

# Autogenerated variables for the problem
balance = 999999
annualInterestRate = 0.18

# Variables
initial_balance = balance
monthly_interest_rate = annualInterestRate / 12.0
low = balance / 12
high = (balance * (1 + monthly_interest_rate)**12)/ 12.0
monthly_payment_guess = (high + low) / 2

month = 0
while True:
    if month > 11:
        if balance <= 0.12 and balance >= 0:
            break
        # Too little money being paid monthly, paying less than
        # what is owed (positive balance at end of 12 months, which
        # means that more money than is actually owed is being paid)
        if balance > 0.12:
            low = monthly_payment_guess
        # Too much money being paid monthly, paying more monthly
        # than what is owed (negative balance at end of 12 months,
        # which means that more money than is actually owed is
        # being paid)
        if balance < 0:
            high = monthly_payment_guess
        # Reset original numbers for next 12 months test
        monthly_payment_guess = (high + low) / 2 # Next guess
        month = 0
        balance = initial_balance
    monthly_unpaid_balance = balance - monthly_payment_guess
    balance = monthly_unpaid_balance + (monthly_interest_rate * monthly_unpaid_balance)
    month += 1
print("Lowest payment: {}".format(round(monthly_payment_guess, 2)))
